hydra:
  run:
    dir: .
  output_subdir: null
env:
  id: "MFG_MS_V8"
  num_envs: 64

train:
  num_steps_per_env: 256 
  num_learning_iterations: 10000 
  empirical_normalization: true

  save_interval: 100  
  experiment_name: Muscle_Skeleton
  run_name: "test"

  logger: wandb  
  wandb_project: Muscle_Skeleton

  # -- load and resuming
  load_run: -1  # -1 means load latest run
  resume_path: null  # updated from load_run and checkpoint
  checkpoint: -1  # -1 means load latest checkpoint
  
  algorithm:
    class_name: PPO
    normalize_advantage_per_mini_batch: false

    value_loss_coef: 0.5
    clip_param: 0.2
    use_clipped_value_loss: true

    desired_kl: 0.02
    entropy_coef: 0.00
    gamma: 0.99
    lam: 0.95
    max_grad_norm: 1.0

    learning_rate: 0.0001
    num_learning_epochs: 15
    num_mini_batches: 12        
    schedule: adaptive        

  
  policy:
    class_name: ActorCritic
    # for MLP i.e. `ActorCritic`
    activation: elu
    actor_hidden_dims: [1024, 512, 256]
    critic_hidden_dims: [1024, 512, 256]
    init_noise_std: 0.1
    noise_std_type: "scalar"  # 'scalar' or 'log'

    # only needed for `ActorCriticRecurrent`
    # rnn_type: 'lstm'
    # rnn_hidden_dim: 512
    # rnn_num_layers: 1
seed: 0
device: "cuda"
log_dir: "./logs"
