# Visualization configuration
env:
  id: "MFG_MS_V7"  # MuJoCo environment ID
  render_mode: "human"  # "human", "rgb_array", or None
  width: 1280          # Render window width
  height: 720          # Render window height

policy:
  checkpoint: "logs/model_5000.pt"  # Path to trained policy
  activation: "elu"
  hidden_dims: [1024, 512, 256]

visualization:
  num_episodes: 100     # Number of episodes to run
  speedup: 1         # Simulation speed multiplier (1.0 = real-time)
  record_video: False  # Save video to files
  video_dir: "videos"  # Where to save recordings
